/* eslint-disable */

import React from 'react';

const CountrySelector = () => (
    <>
    <option defaultValue="FR">France</option>
    <option defaultValue="AF">Afghanistan</option>
    <option defaultValue="ZA">Afrique du sud</option>
    <option defaultValue="AX">Åland, îles</option>
    <option defaultValue="AL">Albanie</option>
    <option defaultValue="DZ">Algérie</option>
    <option defaultValue="DE">Allemagne</option>
    <option defaultValue="AD">Andorre</option>
    <option defaultValue="AO">Angola</option>
    <option defaultValue="AI">Anguilla</option>
    <option defaultValue="AQ">Antarctique</option>
    <option defaultValue="AG">Antigua et barbuda</option>
    <option defaultValue="SA">Arabie saoudite</option>
    <option defaultValue="AR">Argentine</option>
    <option defaultValue="AM">Arménie</option>
    <option defaultValue="AW">Aruba</option>
    <option defaultValue="AU">Australie</option>
    <option defaultValue="AT">Autriche</option>
    <option defaultValue="AZ">Azerbaïdjan</option>
    <option defaultValue="BS">Bahamas</option>
    <option defaultValue="BH">Bahreïn</option>
    <option defaultValue="BD">Bangladesh</option>
    <option defaultValue="BB">Barbade</option>
    <option defaultValue="BY">Bélarus</option>
    <option defaultValue="BE">Belgique</option>
    <option defaultValue="BZ">Belize</option>
    <option defaultValue="BJ">Bénin</option>
    <option defaultValue="BM">Bermudes</option>
    <option defaultValue="BT">Bhoutan</option>
    <option defaultValue="BO">Bolivie, l'état plurinational</option>
    <option defaultValue="BQ">Bonaire, saint eustache et saba</option>
    <option defaultValue="BA">Bosnie herzégovine</option>
    <option defaultValue="BW">Botswana</option>
    <option defaultValue="BV">Bouvet, île</option>
    <option defaultValue="BR">Brésil</option>
    <option defaultValue="BN">Brunei darussalam</option>
    <option defaultValue="BG">Bulgarie</option>
    <option defaultValue="BF">Burkina faso</option>
    <option defaultValue="BI">Burundi</option>
    <option defaultValue="KY">Caïmans, îles</option>
    <option defaultValue="KH">Cambodge</option>
    <option defaultValue="CM">Cameroun</option>
    <option defaultValue="CA">Canada</option>
    <option defaultValue="CV">Cap vert</option>
    <option defaultValue="CF">Centrafricaine, république</option>
    <option defaultValue="CL">Chili</option>
    <option defaultValue="CN">Chine</option>
    <option defaultValue="CX">Christmas, île</option>
    <option defaultValue="CY">Chypre</option>
    <option defaultValue="CC">Cocos (keeling), îles</option>
    <option defaultValue="CO">Colombie</option>
    <option defaultValue="KM">Comores</option>
    <option defaultValue="CG">Congo</option>
    <option defaultValue="CD">Congo, la république démocratique du</option>
    <option defaultValue="CK">Cook, îles</option>
    <option defaultValue="KR">Corée, république de</option>
    <option defaultValue="KP">Corée, république populaire démocratique de</option>
    <option defaultValue="CR">Costa rica</option>
    <option defaultValue="CI">Côte d'ivoire</option>
    <option defaultValue="HR">Croatie</option>
    <option defaultValue="CU">Cuba</option>
    <option defaultValue="CW">Curaçao</option>
    <option defaultValue="DK">Danemark</option>
    <option defaultValue="DJ">Djibouti</option>
    <option defaultValue="DO">Dominicaine, république</option>
    <option defaultValue="DM">Dominique</option>
    <option defaultValue="EG">Égypte</option>
    <option defaultValue="SV">El salvador</option>
    <option defaultValue="AE">Émirats arabes unis</option>
    <option defaultValue="EC">Équateur</option>
    <option defaultValue="ER">Érythrée</option>
    <option defaultValue="ES">Espagne</option>
    <option defaultValue="EE">Estonie</option>
    <option defaultValue="US">États unis</option>
    <option defaultValue="ET">Éthiopie</option>
    <option defaultValue="FK">Falkland, îles (malvinas)</option>
    <option defaultValue="FO">Féroé, îles</option>
    <option defaultValue="FJ">Fidji</option>
    <option defaultValue="FI">Finlande</option>
    <option defaultValue="GA">Gabon</option>
    <option defaultValue="GM">Gambie</option>
    <option defaultValue="GE">Géorgie</option>
    <option defaultValue="GS">Géorgie du sud et les îles sandwich du sud</option>
    <option defaultValue="GH">Ghana</option>
    <option defaultValue="GI">Gibraltar</option>
    <option defaultValue="GR">Grèce</option>
    <option defaultValue="GD">Grenade</option>
    <option defaultValue="GL">Groenland</option>
    <option defaultValue="GP">Guadeloupe</option>
    <option defaultValue="GU">Guam</option>
    <option defaultValue="GT">Guatemala</option>
    <option defaultValue="GG">Guernesey</option>
    <option defaultValue="GN">Guinée</option>
    <option defaultValue="GW">Guinée bissau</option>
    <option defaultValue="GQ">Guinée équatoriale</option>
    <option defaultValue="GY">Guyana</option>
    <option defaultValue="GF">Guyane française</option>
    <option defaultValue="HT">Haïti</option>
    <option defaultValue="HM">Heard et îles macdonald, île</option>
    <option defaultValue="HN">Honduras</option>
    <option defaultValue="HK">Hong kong</option>
    <option defaultValue="HU">Hongrie</option>
    <option defaultValue="IM">Île de man</option>
    <option defaultValue="UM">Îles mineures éloignées des états unis</option>
    <option defaultValue="VG">Îles vierges britanniques</option>
    <option defaultValue="VI">Îles vierges des états unis</option>
    <option defaultValue="IN">Inde</option>
    <option defaultValue="ID">Indonésie</option>
    <option defaultValue="IR">Iran, république islamique d'</option>
    <option defaultValue="IQ">Iraq</option>
    <option defaultValue="IE">Irlande</option>
    <option defaultValue="IS">Islande</option>
    <option defaultValue="IL">Israël</option>
    <option defaultValue="IT">Italie</option>
    <option defaultValue="JM">Jamaïque</option>
    <option defaultValue="JP">Japon</option>
    <option defaultValue="JE">Jersey</option>
    <option defaultValue="JO">Jordanie</option>
    <option defaultValue="KZ">Kazakhstan</option>
    <option defaultValue="KE">Kenya</option>
    <option defaultValue="KG">Kirghizistan</option>
    <option defaultValue="KI">Kiribati</option>
    <option defaultValue="KW">Koweït</option>
    <option defaultValue="LA">Lao, république démocratique populaire</option>
    <option defaultValue="LS">Lesotho</option>
    <option defaultValue="LV">Lettonie</option>
    <option defaultValue="LB">Liban</option>
    <option defaultValue="LR">Libéria</option>
    <option defaultValue="LY">Libye</option>
    <option defaultValue="LI">Liechtenstein</option>
    <option defaultValue="LT">Lituanie</option>
    <option defaultValue="LU">Luxembourg</option>
    <option defaultValue="MO">Macao</option>
    <option defaultValue="MK">Macédoine, l'ex république yougoslave de</option>
    <option defaultValue="MG">Madagascar</option>
    <option defaultValue="MY">Malaisie</option>
    <option defaultValue="MW">Malawi</option>
    <option defaultValue="MV">Maldives</option>
    <option defaultValue="ML">Mali</option>
    <option defaultValue="MT">Malte</option>
    <option defaultValue="MP">Mariannes du nord, îles</option>
    <option defaultValue="MA">Maroc</option>
    <option defaultValue="MH">Marshall, îles</option>
    <option defaultValue="MQ">Martinique</option>
    <option defaultValue="MU">Maurice</option>
    <option defaultValue="MR">Mauritanie</option>
    <option defaultValue="YT">Mayotte</option>
    <option defaultValue="MX">Mexique</option>
    <option defaultValue="FM">Micronésie, états fédérés de</option>
    <option defaultValue="MD">Moldova, république de</option>
    <option defaultValue="MC">Monaco</option>
    <option defaultValue="MN">Mongolie</option>
    <option defaultValue="ME">Monténégro</option>
    <option defaultValue="MS">Montserrat</option>
    <option defaultValue="MZ">Mozambique</option>
    <option defaultValue="MM">Myanmar</option>
    <option defaultValue="NA">Namibie</option>
    <option defaultValue="NR">Nauru</option>
    <option defaultValue="NP">Népal</option>
    <option defaultValue="NI">Nicaragua</option>
    <option defaultValue="NE">Niger</option>
    <option defaultValue="NG">Nigéria</option>
    <option defaultValue="NU">Niué</option>
    <option defaultValue="NF">Norfolk, île</option>
    <option defaultValue="NO">Norvège</option>
    <option defaultValue="NC">Nouvelle calédonie</option>
    <option defaultValue="NZ">Nouvelle zélande</option>
    <option defaultValue="IO">Océan indien, territoire britannique de l'</option>
    <option defaultValue="OM">Oman</option>
    <option defaultValue="UG">Ouganda</option>
    <option defaultValue="UZ">Ouzbékistan</option>
    <option defaultValue="PK">Pakistan</option>
    <option defaultValue="PW">Palaos</option>
    <option defaultValue="PS">Palestinien occupé, territoire</option>
    <option defaultValue="PA">Panama</option>
    <option defaultValue="PG">Papouasie nouvelle guinée</option>
    <option defaultValue="PY">Paraguay</option>
    <option defaultValue="NL">Pays bas</option>
    <option defaultValue="PE">Pérou</option>
    <option defaultValue="PH">Philippines</option>
    <option defaultValue="PN">Pitcairn</option>
    <option defaultValue="PL">Pologne</option>
    <option defaultValue="PF">Polynésie française</option>
    <option defaultValue="PR">Porto rico</option>
    <option defaultValue="PT">Portugal</option>
    <option defaultValue="QA">Qatar</option>
    <option defaultValue="RE">Réunion</option>
    <option defaultValue="RO">Roumanie</option>
    <option defaultValue="GB">Royaume uni</option>
    <option defaultValue="RU">Russie, fédération de</option>
    <option defaultValue="RW">Rwanda</option>
    <option defaultValue="EH">Sahara occidental</option>
    <option defaultValue="BL">Saint barthélemy</option>
    <option defaultValue="SH">Sainte hélène, ascension et tristan da cunha</option>
    <option defaultValue="LC">Sainte lucie</option>
    <option defaultValue="KN">Saint kitts et nevis</option>
    <option defaultValue="SM">Saint marin</option>
    <option defaultValue="MF">Saint martin(partie française)</option>
    <option defaultValue="SX">Saint martin (partie néerlandaise)</option>
    <option defaultValue="PM">Saint pierre et miquelon</option>
    <option defaultValue="VA">Saint siège (état de la cité du vatican)</option>
    <option defaultValue="VC">Saint vincent et les grenadines</option>
    <option defaultValue="SB">Salomon, îles</option>
    <option defaultValue="WS">Samoa</option>
    <option defaultValue="AS">Samoa américaines</option>
    <option defaultValue="ST">Sao tomé et principe</option>
    <option defaultValue="SN">Sénégal</option>
    <option defaultValue="RS">Serbie</option>
    <option defaultValue="SC">Seychelles</option>
    <option defaultValue="SL">Sierra leone</option>
    <option defaultValue="SG">Singapour</option>
    <option defaultValue="SK">Slovaquie</option>
    <option defaultValue="SI">Slovénie</option>
    <option defaultValue="SO">Somalie</option>
    <option defaultValue="SD">Soudan</option>
    <option defaultValue="SS">Soudan du sud</option>
    <option defaultValue="LK">Sri lanka</option>
    <option defaultValue="SE">Suède</option>
    <option defaultValue="CH">Suisse</option>
    <option defaultValue="SR">Suriname</option>
    <option defaultValue="SJ">Svalbard et île jan mayen</option>
    <option defaultValue="SZ">Swaziland</option>
    <option defaultValue="SY">Syrienne, république arabe</option>
    <option defaultValue="TJ">Tadjikistan</option>
    <option defaultValue="TW">Taïwan, province de chine</option>
    <option defaultValue="TZ">Tanzanie, république unie de</option>
    <option defaultValue="TD">Tchad</option>
    <option defaultValue="CZ">Tchèque, république</option>
    <option defaultValue="TF">Terres australes françaises</option>
    <option defaultValue="TH">Thaïlande</option>
    <option defaultValue="TL">Timor leste</option>
    <option defaultValue="TG">Togo</option>
    <option defaultValue="TK">Tokelau</option>
    <option defaultValue="TO">Tonga</option>
    <option defaultValue="TT">Trinité et tobago</option>
    <option defaultValue="TN">Tunisie</option>
    <option defaultValue="TM">Turkménistan</option>
    <option defaultValue="TC">Turks et caïcos, îles</option>
    <option defaultValue="TR">Turquie</option>
    <option defaultValue="TV">Tuvalu</option>
    <option defaultValue="UA">Ukraine</option>
    <option defaultValue="UY">Uruguay</option>
    <option defaultValue="VU">Vanuatu</option>
    <option defaultValue="VE">Venezuela, république bolivarienne du</option>
    <option defaultValue="VN">Viet nam</option>
    <option defaultValue="WF">Wallis et futuna</option>
    <option defaultValue="YE">Yémen</option>
    <option defaultValue="ZM">Zambie</option>
    <option defaultValue="ZW">Zimbabwe​​​​​</option>
	</>
);

export default CountrySelector;